/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {
    public String getGreeting() {
        return "\n#########################\nPublisher Service Started!\n#########################\n";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
