/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void dummyTest() {
        assertTrue(true); // Test toujours vrai pour ne jamais échouer
    }
}
